# Site settings
title: Yuqi's Park
description: A blog about Yuqi
baseurl: "/zack_blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yuqi Zheng
user_description: I am a Entry-level Backend Software Developer.
user_title: I'm a Backend software developer.
email: yuqi95@uw.edu
github_username:  deepforce
gplus_username:  yuqi95@uw.edu

# Google-analytics
google-analytics:
  id: G-EQFQ484NBK

exclude: ['package.json', 'src' , 'node_modules']
