# Site settings
title: Zack's Park
description: A blog about Zack
baseurl: "zack_blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yuqi Zheng (Zack)
user_description: A second-year MLIS student at University of Washington.
user_title: Backend Developer Intern
email: yuqi95@uw.edu
github_username:  deepforce
gplus_username:  yuqi95@uw.edu

# Google-analytics
# google-analytics:
#   id: ""

exclude: ['package.json', 'src' , 'node_modules']
